
agent_name: lail_eb_multiset

agent:
  _target_: agents.lail_eb.LailEbAgent
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  lr: ${lr}
  feature_dim: ${feature_dim}
  hidden_dim: 1024
  critic_target_tau: 0.01
  num_expl_steps: 2000
  update_every_steps: 2
  stddev_schedule: ${stddev_schedule}
  stddev_clip: 0.3
  use_tb: ${use_tb}
  reward_d_coef: 2.0
  discriminator_lr: ${discriminator_lr}
  spectral_norm_bool: ${spectral_norm_bool}
  check_every_steps: ${check_every_steps}
  log_std_bounds: [-5, 2]
  GAN_loss: ${GAN_loss}
  stochastic_encoder: ${stochastic_encoder}
  train_encoder_w_critic: ${train_encoder_w_critic}
  from_dem: ${from_dem}
  noise_sigma: ${noise_sigma}
  depth_flag: ${depth_flag}
  segm_flag: ${segm_flag}

